### ISSUE TITLE
[bug] input type=file multiple is not working 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-v3#1006]
https://youtu.be/qxhPjAsBu5k
You will not able to select multiple file. I know there are imagepicker and photolibrary to select multiple image to upload. But i want to select multiple files like docx, docs, xls and pdf 

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

**Current behavior:**
it is not allowing to me select multiple file.

**Expected behavior:**
it should allow me to select multiple file.

**Steps to reproduce:**

**Related code:**

```
Github Repo: https://github.com/indraraj26/input-file-multiple
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v8.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Comment by indraraj26** [comment]
Also this is not working
````
<input type="datetime-local" step="900">
````

**Comment by longgt** [comment]
https://caniuse.com/#feat=input-file-multiple

Partial supports in Chrome 75 for Android 5.x.

**Comment by mohitceo** [comment]
bro use ionic image picker for multiple images and transfer with file transfer
