### ISSUE TITLE
App doesn't scroll on when closing an actionSheet (ios and ios safari)

### ISSUE THREAD

**Issue by hugomota** [ionic-team/ionic-v3#1013]
When I close an actionSheet I can't scroll on my app. My app only begins to scroll again when I perform another action (like tap on a button etc)

This doesn't happen on chrome I can only reproduce on ios and ios safari. I don't have a clue about what is happening. There is no invisible overlay because I can tap and click on the elements "belllow"

```
this.actionSheet.create({
      buttons: [
        { text: "All Jobs", handler: () => { this.filterBy = "all"; }},
        { text: "Completed Jobs", handler: () => { this.filterBy = "completed"; }},
        { text: "Cancel", role: "cancel" }
      ]
    }).present();
```

**Other information:**
Using "ionic-angular": "3.9.2",

**Comment by hugomota** [comment]
Forgot to mention but this alo happens when using the <ion-select>

**Comment by longgt** [comment]
Maybe duplicate of #1004

**Comment by hugomota** [comment]
Yes... Same thing! Installing the latest did solve the problem. Thanks!
