### ISSUE TITLE
bug: [high] ion-option selected is not working with form

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-v3#1022]
**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

**Current behavior:**

```
<ion-option selected>select name</ion-option>
```
selected option is not showing when it is using with form

**Expected behavior:**

```
<ion-option selected>select name</ion-option>
```
selected option should show even with form

**Steps to reproduce:**

**Related code:**

I have added with form vs without form
https://stackblitz.com/edit/ionic-mx8iug?file=pages%2Fhome%2Fhome.html

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
{
  "name": "ionic-mx8iug",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "rxjs": "5.4.0",
    "core-js": "2.4.1",
    "zone.js": "0.8.12",
    "typescript": "2.3.4",
    "@angular/core": "5.2.9",
    "@angular/http": "4.1.3",
    "ionic-angular": "3.9.2",
    "@angular/forms": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9"
  }
}
```

**Comment by indraraj26** [comment]
i tried to debug both time i get the value in _value array but it is not updating with form

````
Object.defineProperty(Select.prototype, "options", {
        /**
         * @private
         */
        set: function (val) {
            this._options = val;
            debugger;
            var values = this.getValues();
            debugger;
            if (values.length === 0) {
                // there are no values set at this point
                // so check to see who should be selected
                // we use writeValue() because we don't want to update ngModel
                this.writeValue(val.filter(function (o) { return o.selected; }).map(function (o) { return o.value; }));
                debugger;
            }
            else {
                this._updateText();
            }
        },
        enumerable: true,
        configurable: true
    });
````

**Comment by longgt** [comment]
I think you should set the value of `ion-option` explicitly such as empty string instead of `undefined`.
In console, we can see if we didn't specify any value to `ion-option`, it takes `text` as value.
When I tried to set value to empty string, it works as exptected.

ts
```
addPerson: any {
  user: ''
}
```

html
```
<ion-option value="" selected>select name</ion-option>
```

**Comment by indraraj26** [comment]
yes this works. Ionic team should have mentioned that it needs to be specify in order show default selected in form. 
Thank you.
