### ISSUE TITLE
iOS App Store publishment fails: ITMS-90338 - Non-public API usage - _setAlwaysRunsAtForegroundPriority

### ISSUE THREAD

**Issue by SimoneMSR** [ionic-team/ionic-v3#1042]
**I'm submitting a ...** 
[x] bug report
[ ] feature request

Following this cordova unresolved [issue](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/209) about `cordova-plugin-ionic-webview`, I have decided to open the issue also here, on the official/root channel.
The problem arises for the use of a function `_setAlwaysRunsAtForegroundPriority` that I have not written: this is in some library I use.

**Current behavior:**
I receive this notice after successfully uloading the ipa to App Store Connect

> Dear Developer,
> We identified one or more issues with a recent delivery for your app,*****. Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in *****: _setAlwaysRunsAtForegroundPriority:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Best regards,The App Store Team |   |   | Dear Developer,We identified one or more issues with a recent delivery for your app, "Vitruvio" 1.1 (1.1). Please correct the following issues, then upload again.ITMS-90338: Non-public API usage - The app references non-public selectors in Panatta Plus: _setAlwaysRunsAtForegroundPriority:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
> 
> If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Best regards,
> 
> The App Store Team

My current cordova libraries are:
```
"cordova-android": "8.0.0",
"cordova-browser": "6.0.0",
"cordova-ios": "5.0.1",
"cordova-plugin-add-swift-support": "2.0.2",
"cordova-plugin-camera": "^4.0.3",
"cordova-plugin-device": "^2.0.2",
"cordova-plugin-file": "^6.0.1",
"cordova-plugin-file-transfer": "^1.7.1",
"cordova-plugin-ionic": "^5.3.0",
"cordova-plugin-ionic-keyboard": "^2.1.3",
"cordova-plugin-ionic-webview": "4.1.0",
"cordova-plugin-network-information": "2.0.1",
"cordova-plugin-qrscanner": "^3.0.1",
"cordova-plugin-splashscreen": "^5.0.2",
"cordova-plugin-statusbar": "^2.4.2",
"cordova-plugin-whitelist": "^1.3.3",
"cordova.plugins.diagnostic": "^4.0.12"
```

Ionic is: 
`"ionic-angular": "3.9.2",`

**Related code:**
I have not written a function with that name. So I cannot share any code.

**Other information:**
Uneffective solutions I tried are:
-https://stackoverflow.com/questions/54373661/how-to-resolve-app-validation-the-appreferences-non-public-selectors-in-payloa/56934236#56934236
-https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/209

**Comment by Dave-Nandwa** [comment]
Hi, I'm also facing this exact issue and I'm also trying to upload my app today. Please let me know if you get a workaround. Thanks.

**Comment by chris087** [comment]
Same issue here...

**Comment by SimoneMSR** [comment]
The issued is solved [here](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/209#issuecomment-509600208).
