### ISSUE TITLE
[ion-toggle] [Android] Accessibility Mode Double-Tap Does Not Switch the State of ion-toggle

### ISSUE THREAD

**Issue by bryplano** [ionic-team/ionic-v3#1061]
## I'm submitting a ...
[x] bug report
[ ] feature request

## Current behavior:

When using an Android device and attempting to use an `ion-toggle` in an Ionic 3 application in accessibility mode, the `ion-toggle` will not change states (ex. if "on", double-tapping will not set the toggle to "off").

~This only occurs on Samsung devices and only in when using the Voiceover Accessibility Mode.~ Previously denoted this was only Samsung devices, but it also occurs on a Google Pixel 2 with Android 10.

Better explanation / rewrite of #504. This is an issue as of the latest version of Ionic 3.

## Expected behavior:

The `ion-toggle` should switch from on to off or off to on, depending on the state when double-tapped.

## Steps to reproduce:

**Note**: These reproduction steps assume you have properly downloaded and initialized / installed the sample application from "Related code" (below). You will need Android Studio to install directly to a test device.

Test Device: Samsung Galaxy S8 running Android 8.0.0 (Patch June 1st 2018), Google Pixel 2 Android 10 (Sec Patch Sept 5 2019).

1. Turn VoiceOver mode on for your device (on the GS8, go to **Settings** -> **Accessibility** -> **Vision** -> **Voice Assistant** (turn on))
2. Navigate to the sample Ionic application
3. When the app loads, single-tap on a toggle. This will announce the toggle to you via VoiceOver and display the green selection box around it.
4. Double tap anywhere on the screen to attempt to change the state of the toggle. Per the issue, VoiceOver will simply announce the toggle's current state without changing it.

## Related code:

**Sample App Repo**: https://github.com/bryplano/IonToggleTest

Lines of interest: https://github.com/bryplano/IonToggleTest/blob/master/src/pages/home/home.html#L12

## Other information:

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI          : 5.2.8
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 
4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.16.3
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a
```

**Comment by bryplano** [comment]
**Note**: This is not an issue in Ionic 4. Best LTS suggestion is to upgrade to the latest version of Ionic.

**Comment by bryplano** [comment]
Updated this issue - it is not just a problem on Samsung devices.

**Comment by liamdebeasi** [comment]
This issue has been fixed and will be available in the next release of Ionic 3.
