### ISSUE TITLE
Ionic app crashes on Android 9 (Mostly Samsung phones and others)

### ISSUE THREAD

**Issue by iftikharyk** [ionic-team/ionic-v3#1063]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

When I build an app using **ionic Cordova run android** or **installing debug .apk directly** the app works fine on the first run. As soon as I close the app and rerun it and tap on anything the app crashes and closes automatically.
I have tried many things, like
**- I added this in AndroidManifest.xml**
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="28" />
```
But nothing solves the issue. While searching i have encountered any forums which resemble my problem in a different way but results are quite similar.

**Expected behavior:**

The app should work as expected like it is running on **Android 8 or below**

**Steps to reproduce:**

Any app in which you will use the plugins I am using may reproduce the issue.

**Related code: Package.json**

```
{
  "name": "Sample App",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/camera": "~4.17.0",
    "@ionic-native/core": "~4.17.0",
    "@ionic-native/geolocation": "^4.17.0",
    "@ionic-native/in-app-browser": "~4.17.0",
    "@ionic-native/keyboard": "~4.17.0",
    "@ionic-native/location-accuracy": "^3.14.0",
    "@ionic-native/onesignal": "^3.14.0",
    "@ionic-native/speech-recognition": "~4.17.0",
    "@ionic-native/splash-screen": "~4.17.0",
    "@ionic-native/status-bar": "^3.14.0",
    "@ionic/storage": "2.2.0",
    "@types/intro.js": "^2.4.5",
    "angular2-swing": "^0.14.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-camera": "4.0.3",
    "cordova-plugin-device": "1.1.7",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-geolocation": "4.0.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-request-location-accuracy": "2.3.0",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "intro.js": "^2.9.3",
    "ionic-angular": "3.9.2",
    "ionic-img-viewer": "^2.9.0",
    "ionic-plugin-deeplinks": "1.0.20",
    "ionic-plugin-keyboard": "2.2.1",
    "ionicons": "3.0.0",
    "onesignal-cordova-plugin": "2.4.7",
    "pretty-checkbox": "^3.0.3",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.1",
    "@ionic/lab": "1.0.16",
    "typescript": "~2.6.2",
    "ws": "3.3.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-speechrecognition": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "onesignal-cordova-plugin": {},
      "cordova-plugin-request-location-accuracy": {
        "PLAY_SERVICES_LOCATION_VERSION": "16.+"
      },
      "cordova-plugin-statusbar": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\iftikhar.khan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 9.0.0 (cordova-lib@9.0.1)

local packages:

    @ionic/app-scripts : 3.2.1
    Cordova Platforms  : android 7.1.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : Windows 10
```

When I use **adb logcat** I got this.

![error android](https://user-images.githubusercontent.com/34522152/66116405-1b070c00-e5ec-11e9-8a59-0ebf19b32db2.PNG)

**Comment by StefanRein** [comment]
Hey, can you provide a GitHub repository?

Just a wild guess: If I remember correctly, since some Android Version you would need first to ask the user for permission to use native features otherwise it should crash (at least on iOS for sure).

**Comment by iftikharyk** [comment]
I regret to inform you that I can't provide the repo because that's confidential project.
But our team managed to dig out the issues and found that it's the **Android System Web View** that is messing with the application.
For that purpose, we used a Crosswalk-webview plugin that manages to replace the default webview to its own. But sadly it is causing some rendering issues inside the app. Some of the items are showing and some are don't. We thought it might be the front-end bug or something, but it isn't.

The eye of the bull is that ionic should make some changes in their latest ionic 4 to overcome this issue so we may not get this issue in the future because right now this problem is on Android OS 9, we don't know what issues might we face in the latest Android 10. So @IonicProSupport should look into this.

**Comment by StefanRein** [comment]
@iftikharyk Hm. Our application (ionic 3) works fine on Android 9 and all the other versions and iOS, iPad OS. We just found some other bugs in Safari on iOS 13. If I have time, I will setup a simple project and check this one, too.
