### ISSUE TITLE
Cannot scroll <ion-content> on iOS device

### ISSUE THREAD

**Issue by hasancansaral** [ionic-team/ionic-v3#1065]
**I'm submitting a ...**
[x] bug report
[  ] feature request

**Current behavior:**
Cannot scroll in `<ion-content>`. I have a tabbar application, and have Account view on my last tab. When I click on it the first time, I cannot scroll `<ion-content>`. However, when I change tab and re-visit it, I start to be able to scroll.

When I visit the view the first time, if I click on an `<ion-input>` and focus on it, I can again scroll.

This only happens on an iOS device. Works as expected on Android and even on iOS Simulator.

**Expected behavior:**
To be able to scroll the very first time, without having to touch on an input.

**Related code:**
There's a form and a `<p>` tag within `<ion-content>`:

    <h2 ion-text text-center color="light" class="all-text" id="name" {{staticMember?.name}}</h2>
    <ion-item [ngClass]="{'lp-invalid-input': account.get('name').invalid && (account.get('name').dirty || account.get('name').touched)}">
        <ion-input [formControl]="account.controls['name']" type="text"></ion-input>
    </ion-item>
    ... Couple of more <ion-item>

And in my `.ts`:

    constructor(...) {
            this.account = this.formBuilder.group({
                name: new FormControl('', [Validators.required]),
                email: new FormControl('', [Validators.required, Validators.email]),
                msisdn: new FormControl('', [Validators.required]),
                whatsappMsisdn: new FormControl(''),
                loyaltyProgram: new FormControl(null),
                password: new FormControl(this.TEMP_PASSWORD),
                confirmPassword: new FormControl(this.TEMP_PASSWORD)
            });
        }

    ionViewDidEnter(){
            this.statusBar.styleLightContent();
            let loading = this.loadingCtrl.create({
                content: 'Please wait...'
            });
            
            loading.present();
            
            this.http.get(Properties.API_URL + Properties.ACCOUNT_ENDPOINT).toPromise()
            .then((res) => {
                this.staticMember = JSON.parse(JSON.stringify(res.body));
                this.account.patchValue(res.body);
                this.hideWhatsapp = this.account.get('msisdn').value === this.account.get('whatsappMsisdn').value;
                this.loyaltyProgramText = res.body['loyaltyProgram'] ? res.body['loyaltyProgram'].name + ' - ' + res.body['loyaltyProgram'].airlineTierName : 'No Loyalty Program';
                if(res.body['loyaltyProgram']) this.account.controls['loyaltyProgram'].setValue({id: res.body['loyaltyProgram'].id});
                else this.account.controls['loyaltyProgram'].setValue(0);
            })
            .finally(() => {
                loading.dismiss();
            });
        }

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI          : 5.4.2
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/hasancansaral/Library/Android/sdk)
   ios-sim           : 8.0.1
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a
```

**Comment by longgt** [comment]
Duplicate of #1005
Update ionic-angular to **latest** may solve your problem.

**Comment by hasancansaral** [comment]
`npm i ionic-angular@latest` solved my problem.
