### ISSUE TITLE
ionic 3 build fails with --aot flag: @angular\compiler-cli\diagnostic error.

### ISSUE THREAD

**Issue by sarthakbhatt16** [ionic-team/ionic-v3#1085]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**
I am trying to get a production build of my application for my client.
If I take out --aot option from the production build, the build is successful.
But with the --aot flag, the build gives error as shown in the attached image.

![error forum](https://user-images.githubusercontent.com/25870595/72295822-5327dd00-3626-11ea-886d-701aa983ce5b.jpeg)

Also, I am attaching the screenshot of my error log while building the application.
Kindly help with any leads on this issue. I have been trying on this from the last 6 days continuously so far. I tried almost all possible suggestions from the related issues on the forum. Thanks in advance.

**Expected behavior:**

```

```

**Other information:**
**package.json***
This is what my package.json looks like:

{
“name”: “XXXXXX”,
“version”: “0.0.1”,
“author”: “Ionic Framework”,
“homepage”: “http://ionicframework.com/”,
“private”: true,
“scripts”: {
“clean”: “ionic-app-scripts clean”,
“build”: “ionic-app-scripts build”,
“lint”: “ionic-app-scripts lint”,
“ionic:build”: “ionic-app-scripts build”,
“ionic:serve”: “ionic-app-scripts serve”,
“test”: “ng test”
},
“dependencies”: {
“@agm/core”: “^1.0.0-beta.2”,
“@angular/cli”: “1.1.3”,
“@angular/common”: “4.1.3”,
“@angular/compiler”: “4.1.3”,
“@angular/compiler-cli”: “^4.4.7”,
“@angular/core”: “4.1.3”,
“@angular/forms”: “4.1.3”,
“@angular/http”: “4.1.3”,
“@angular/platform-browser”: “4.1.3”,
“@angular/platform-browser-dynamic”: “4.1.3”,
“@angular/router”: “4.1.3”,
“@feathersjs/client”: “^3.5.6”,
“@feathersjs/feathers”: “^3.2.0”,
“@feathersjs/socketio-client”: “^1.1.1”,
“@ionic-native/base64”: “^4.11.0”,
“@ionic-native/core”: “^3.14.0”,
“@ionic-native/deeplinks”: “^4.11.0”,
“@ionic-native/diagnostic”: “^4.15.0”,
“@ionic-native/document-viewer”: “^4.11.0”,
“@ionic-native/file”: “^4.11.0”,
“@ionic-native/file-chooser”: “^4.11.0”,
“@ionic-native/file-opener”: “^4.15.0”,
“@ionic-native/file-path”: “^4.11.0”,
“@ionic-native/file-picker”: “^4.11.0”,
“@ionic-native/geolocation”: “^4.10.1”,
“@ionic-native/image-picker”: “^4.11.0”,
“@ionic-native/keyboard”: “^3.12.1”,
“@ionic-native/native-audio”: “^4.15.0”,
“@ionic-native/network”: “^4.11.0”,
“@ionic-native/push”: “^4.17.0”,
“@ionic-native/screen-orientation”: “^4.11.0”,
“@ionic-native/splash-screen”: “^3.10.2”,
“@ionic-native/status-bar”: “^3.14.0”,
“@ionic/cloud-angular”: “^0.12.0”,
“@ionic/storage”: “^2.1.3”,
“@types/socket.io-client”: “^1.4.32”,
“android-versions”: “^1.3.0”,
“angular-linky”: “^1.2.2”,
“array-unique”: “^0.3.2”,
“aws-sdk”: “^2.287.0”,
“body-parser”: “^1.18.3”,
“code-push”: “^2.0.4”,
“com-badrit-base64”: “^0.2.0”,
“com.synconset.imagepicker”: “^2.1.10”,
“cordova-android”: “6.3.0”,
“cordova-android-support-gradle-release”: “^1.4.7”,
“cordova-ios”: “4.5.5”,
“cordova-plugin-camera”: “^2.4.1”,
“cordova-plugin-compat”: “^1.2.0”,
“cordova-plugin-console”: “^1.1.0”,
“cordova-plugin-device”: “^1.1.7”,
“cordova-plugin-dialogs”: “^2.0.1”,
“cordova-plugin-document-viewer”: “^0.9.10”,
“cordova-plugin-file”: “^6.0.1”,
“cordova-plugin-file-opener2”: “^2.0.19”,
“cordova-plugin-file-transfer”: “^1.7.1”,
“cordova-plugin-filechooser”: “^1.0.1”,
“cordova-plugin-filepath”: “^1.5.1”,
“cordova-plugin-filepicker”: “^1.1.5”,
“cordova-plugin-nativeaudio”: “^3.0.9”,
“cordova-plugin-network-information”: “^2.0.1”,
“cordova-plugin-screen-orientation”: “^3.0.1”,
“cordova-plugin-splashscreen”: “^5.0.2”,
“cordova-plugin-statusbar”: “^2.4.2”,
“cordova-plugin-telerik-imagepicker”: “^2.2.2”,
“cordova-plugin-twilio-video-v2preview”: “^0.3.0”,
“cordova-plugin-video-thumbnail”: “^2.0.1”,
“cordova-plugin-whitelist”: “^1.3.3”,
“cordova-plugin-zip”: “^3.1.0”,
“cordova-sqlite-storage”: “^2.5.2”,
“cordova.plugins.diagnostic”: “^4.0.10”,
“cors”: “^2.8.4”,
“crypto”: “^1.0.1”,
“crypto-js”: “^3.1.9-1”,
“dragula”: “^3.4.0”,
“es6-promise-plugin”: “^4.2.2”,
“express”: “^4.16.3”,
“feathers”: “^2.2.4”,
“feathers-authentication”: “^1.3.1”,
“feathers-client”: “^2.4.0”,
“feathers-hooks”: “^2.1.2”,
“feathers-socketio”: “^2.0.1”,
“file-system”: “^2.2.2”,
“ionic-plugin-deeplinks”: “^1.0.17”,
“ionic-plugin-keyboard”: “^2.2.1”,
“ionicons”: “3.0.0”,
“moment”: “^2.22.2”,
“mongoose”: “^4.13.14”,
“morgan”: “^1.9.0”,
“ng2-img-cropper”: “^0.9.0”,
“ng2-pdf-viewer”: “^5.1.0”,
“ngx-pipes”: “^1.7.0”,
“phonegap-plugin-push”: “~2.1.2”,
“random-string-generator”: “^0.1.0”,
“raven-js”: “^3.27.0”,
“rxjs”: “5.1.1”,
“rxjs-compat”: “^6.5.3”,
“socket.io-client”: “^2.1.1”,
“sw-toolbox”: “3.6.0”,
“ts-md5”: “^1.2.4”,
“twilio-chat”: “^3.2.2”,
“twilio-video”: “^1.18.1”,
“webpack”: “^2.7.0”,
“webpack-dev-server”: “^2.11.2”,
“zone.js”: “^0.9.0”
},
“devDependencies”: {
“@ionic/app-scripts”: “^3.2.4”,
“@ionic/cli-plugin-cordova”: “1.6.1”,
“@ionic/cli-plugin-ionic-angular”: “1.4.1”,
“@ionic/lab”: “1.0.7”,
“@types/googlemaps”: “^3.30.11”,
“@types/jasmine”: “^2.8.8”,
“@types/node”: “^8.10.24”,
“codecov”: “^3.0.4”,
“ionic”: “3.10.3”,
“ionic-angular”: “^3.9.2”,
“ionic-mocks”: “^0.6.0”,
“jasmine-core”: “^2.99.1”,
“jasmine-spec-reporter”: “^4.2.1”,
“karma”: “^3.0.0”,
“karma-chrome-launcher”: “^2.2.0”,
“karma-jasmine”: “^1.1.2”,
“karma-mocha-reporter”: “^2.2.5”,
“karma-remap-istanbul”: “^0.6.0”,
“ts-node”: “^3.3.0”,
“tslint”: “^5.11.0”,
“tslint-eslint-rules”: “^4.1.1”,
“typescript”: “2.3.3”,
“webpack-merge”: “^4.1.4”
},
“description”: “An Ionic project”,
“cordova”: {
“plugins”: {
“cordova-plugin-console”: {},
“cordova-plugin-device”: {},
“cordova-plugin-splashscreen”: {},
“cordova-plugin-whitelist”: {},
“ionic-plugin-keyboard”: {},
“cordova-sqlite-storage”: {},
“cordova-plugin-camera”: {
“CAMERA_USAGE_DESCRIPTION”: " ",
“PHOTOLIBRARY_USAGE_DESCRIPTION”: " "
},
“com-badrit-base64”: {},
“com.synconset.imagepicker”: {
“PHOTO_LIBRARY_USAGE_DESCRIPTION”: “your usage message”
},
“cordova-plugin-zip”: {},
“cordova-plugin-network-information”: {},
“cordova-plugin-screen-orientation”: {},
“cordova-plugin-file-opener2”: {},
“cordova-android-support-gradle-release”: {
“ANDROID_SUPPORT_VERSION”: “26.+”
},
“cordova-plugin-document-viewer”: {},
“cordova-plugin-filepicker”: {},
“cordova-plugin-video-thumbnail”: {},
“ionic-plugin-deeplinks”: {
“URL_SCHEME”: “myapp”,
“DEEPLINK_SCHEME”: “https”,
“DEEPLINK_HOST”: “herokuapp.com”,
“ANDROID_PATH_PREFIX”: “/”,
“ANDROID_2_PATH_PREFIX”: “/”,
“ANDROID_3_PATH_PREFIX”: “/”,
“ANDROID_4_PATH_PREFIX”: “/”,
“ANDROID_5_PATH_PREFIX”: “/”,
“DEEPLINK_2_SCHEME”: " ",
“DEEPLINK_2_HOST”: " ",
“DEEPLINK_3_SCHEME”: " ",
“DEEPLINK_3_HOST”: " ",
“DEEPLINK_4_SCHEME”: " ",
“DEEPLINK_4_HOST”: " ",
“DEEPLINK_5_SCHEME”: " ",
“DEEPLINK_5_HOST”: " "
},
“cordova-plugin-twilio-video-v2preview”: {
“CAMERA_USAGE_DESCRIPTION”: “Camera”,
“MICROPHONE_USAGE_DESCRIPTION”: “Microphone”
},
“cordova-plugin-filechooser”: {},
“cordova-plugin-file”: {},
“cordova-plugin-file-transfer”: {},
“cordova-plugin-compat”: {},
“cordova.plugins.diagnostic”: {},
“cordova-plugin-nativeaudio”: {},
“phonegap-plugin-push”: {
“SENDER_ID”: “XXXXXXXXX”,
“FCM_VERSION”: “11.6.2”
},
“cordova-plugin-statusbar”: {},
“cordova-plugin-filepath”: {}
},
“platforms”: [
“ios”,
“android”
]
},
“config”: {
“ionic_webpack”: “./src/config/webpack.config.js”,
“ionic_dependency_tree”: “./src/config/webpack.config.js”,
“ionic_copy”: “./scripts/copy-mobiscroll-css.js”
}
}

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
@ionic/cli-utils  : 1.10.2
ionic (Ionic CLI) : 3.10.3
```

Android SDK Tools : 26.1.1
Node              : v8.11.1
npm               : 5.6.0 
OS                : macOS

Cordova CLI : 8.0.0 

@ionic/cli-utils  : 1.10.2
ionic (Ionic CLI) : 3.10.3

**Comment by longgt** [comment]
@sarthakbhatt16 could you try again with `--verbose` flag and attach error log?

**Comment by longgt** [comment]
@sarthakbhatt16 you can take a look at this following message and try again
https://github.com/ionic-team/ionic-app-scripts/issues/1309#issuecomment-343990321
