### ISSUE TITLE
The page switching animation time slows down in iOS 14 Beta 3

### ISSUE THREAD

**Issue by angelofan** [ionic-team/ionic-v3#1115]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The page switching animation time slows down in iOS 14 Beta 3.

I just updated iOS 14 Beta 3 today, and the page switching animation is obviously slower than before. It was normal in the previous Beta2 and Beta1 versions.

**Expected behavior:**

The time of page switching animation is consistent with iOS 13

**Steps to reproduce:**

Run the ionic3 application in iOS 14 Beta 3, switch pages, and observe the page switching animation.

I am not sure if there is such a problem in ionic4.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI          : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.0.0-beta.17

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 30 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : not installed

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v14.4.0 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.6 Build version 11E708

```

**Comment by angelofan** [comment]
# Current behavior 
![Current behavior](https://user-images.githubusercontent.com/20255750/88353932-e722f000-cd91-11ea-96ce-2717edf70a4c.gif)

---

# Expected behavior
![Expected behavior](https://user-images.githubusercontent.com/20255750/88354063-46810000-cd92-11ea-919f-5cbc71b56901.gif)

**Comment by oddcb** [comment]
Seems to be a bug in webkit. More information can be found here: https://github.com/ionic-team/ionic-framework/issues/21613

**Comment by angelofan** [comment]
You are right.
