### ISSUE TITLE
Can I make a slack-like sidemenu in ionic 3?

### ISSUE THREAD

**Issue by wiadev** [ionic-team/ionic-v3#950]
Hi
I'm building a mobile app in ionic and I wanna make a slack-like side menu by placing slides.

For example, when you click on main menu item, it will slide out another slide in the sidemenu as slack does.

I tried to use ion-slides in ion-menu but slides is not working.

Check out the screenshot, please.

![stack](https://user-images.githubusercontent.com/18234060/51846561-aa765580-22ce-11e9-8d36-a86335ac6c9c.gif)

Here is the code snippet.
```
<ion-menu [content]="mycontent" [swipeEnabled]="false">
    <ion-content>

      <ion-slides>
        <ion-slide>
          <h1>Slide 1</h1>
        </ion-slide>
        <ion-slide>
          <h1>Slide 2</h1>
        </ion-slide>
        <ion-slide>
          <h1>Slide 3</h1>
        </ion-slide>
      </ion-slides>

  </ion-content>

</ion-menu>

<ion-nav #mycontent [root]="rootPage"></ion-nav>
```
Here is what I'm trying to build.
<img width="380" alt="qqpib" src="https://user-images.githubusercontent.com/18234060/51846580-b530ea80-22ce-11e9-8b59-c2721587874b.png">
Any thoughts on how to implement this?

Thanks.

**Comment by liamdebeasi** [comment]
Hi there, thanks for opening an issue with us! I am going to close this issue as it is more of a support question. I suggest you ask your question on our [forum](https://forum.ionicframework.com/) or [slack](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
