### ISSUE TITLE
Modal delay in opening

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-v3#965]
**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**

Modal opening in after some second

**Expected behavior:**

Modal opening after some second but it should open same as for small array list

**Steps to reproduce:**
download my github repo and run 

**Related code:**

modal issue github: https://github.com/indraraj26/modal-issue

modal delay in opening apk link : https://i.diawi.com/3SNzxM

modal issue youtube : https://www.youtube.com/watch?v=_AuN-9p8opY

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
C:\Users\HP\Downloads\modal-issue-master\modal-issue-master>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v8.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10


C:\Users\HP\Downloads\modal-issue-master\modal-issue-master>
```

**Comment by joe-scotto** [comment]
Seconding this issue. I'm using modals for signup/register forms... it shouldn't have a delay before showing

**Comment by brenden-t-r** [comment]
Also facing this issue.
