### ISSUE TITLE
(ionScroll) and all other custom events don't work when <ion-content> is added with delay

### ISSUE THREAD

**Issue by heidji** [ionic-team/ionic-v3#971]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
```html
<ion-content *ngIf="delay" padding (ionScroll)="test()">
<!-- content -->
</ion-content>
```

```typescript
export class TestPage {
    delay = false;

    constructor(public navCtrl: NavController, public navParams: NavParams) {
    }

    ionViewDidLoad() {
        setTimeout(() => {
            this.delay = true;
        }, 1000)
    }

    test() {
        console.log('scrolling')
    }

}
```
-> the event never fires, the log is empty

**Expected behavior:**
The events are usable

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.10.3 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 4 other plugins)

System:

   NodeJS : v8.12.0 (D:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by longgt** [comment]
Duplicate of https://github.com/ionic-team/ionic/issues/14575

**Comment by heidji** [comment]
@longgt I will go ahead and ask without testing myself. the resize() method restores the scroll events?

**Comment by longgt** [comment]
@heidji it restores the scroll events only if called after content was rendered.
For example, with your code, the content will be rendered after 1000ms. But it takes more time to render all. We need to add some tricky like this

```
  @ViewChild(Content)
  content: Content;

  ionViewDidLoad() {
        setTimeout(() => {this.delay = true;}, 1000);
        setTimeout(() => this.content.resize(), 1500);
  }
```

**Comment by heidji** [comment]
great, i'll take your word for it.
