### ISSUE TITLE
virtual scroll is not working filter searchbar [high]

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-v3#975]
if you type so fast then erase everything from searchbar you will get blank page
if you scroll down to bottom and search for first 10 item you wont get that in filter

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
i get blank dom instead of filter item 

**Expected behavior:**
i should not get blank dom and i should get filtered item whether i am at bottom of list

**Steps to reproduce:**
i will share soon with code
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v8.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by aspoonemore** [comment]
I am able to duplicate this as well
